const projects = [
  { n:'01', name:'SmartWeb', eyebrow:'PRODUCT / SAAS', title:'Infraestructura digital para negocios que necesitan crecer.', desc:'Una plataforma para convertir sitios aislados en una infraestructura digital reutilizable: contenido, SEO, WhatsApp, módulos y evolución multi-tenant.', role:'Product design · UX · Development', problem:'Negocios locales con presencia digital fragmentada y procesos que dependen de herramientas separadas.', outcome:'Un sistema reutilizable que conecta presencia web, contenido, adquisición y operación.', tags:['Next.js','TypeScript','Supabase','PostgreSQL','Vercel'], repo:'https://github.com/popnegro/smartweb', visual:'saas' },
  { n:'02', name:'MuniBrain', eyebrow:'AI / CIVIC TECH', title:'De un problema público a un PMV accionable.', desc:'Motor de descubrimiento y análisis que transforma consultas en propuestas estructuradas con alcance, presupuesto, timeline, KPIs y riesgos.', role:'Product concept · AI UX · Frontend', problem:'Ideas y necesidades difíciles de convertir rápidamente en iniciativas concretas y evaluables.', outcome:'Una experiencia que estructura el problema y lo traduce en una propuesta de intervención.', tags:['Next.js 15','React 19','AI UX','Recharts','shadcn/ui'], repo:'https://github.com/popnegro/munibrain', visual:'ai' },
  { n:'03', name:'Grupo Comunicarte', eyebrow:'PLATFORM / COMMERCIAL', title:'Una plataforma comercial para hacer visible el inventario.', desc:'Ecosistema que conecta landing pública, mapa de soportes, inventario, dashboard, MediaKit y gestión comercial.', role:'UX · Product design · Web development', problem:'Inventario y oportunidades comerciales que necesitan una capa digital más clara para ser descubiertos y gestionados.', outcome:'Un sistema que conecta ubicación, inventario y herramientas comerciales en una misma experiencia.', tags:['React','TypeScript','Maps','Dashboard','MediaKit'], repo:'https://github.com/popnegro/grupo-comunicarte-refactoring', visual:'map' },
  { n:'04', name:'Emilia Sandobar', eyebrow:'UX / LEGAL', title:'Una experiencia digital que convierte confianza en consulta.', desc:'Sitio editorial para servicios legales con arquitectura por rutas, SEO técnico, formularios, CTAs de consulta y validación E2E.', role:'UX/UI · Content structure · Development', problem:'Un servicio profesional necesita explicar valor y generar confianza antes del primer contacto.', outcome:'Una experiencia editorial enfocada en claridad, autoridad y solicitud de consulta.', tags:['React 19','TypeScript','Vite','Tailwind','Playwright'], repo:'https://github.com/popnegro/abogadasandobar', visual:'editorial' },
  { n:'05', name:'SmartBarrio', eyebrow:'LOCAL COMMERCE', title:'Presencia y descubrimiento para la economía de proximidad.', desc:'Exploración de marketplace y servicios digitales para negocios de barrio, conectando descubrimiento, presencia y oportunidades comerciales.', role:'Product concept · UX · Business model', problem:'Los negocios de proximidad necesitan ser encontrados y conectarse mejor con su demanda local.', outcome:'Una propuesta de infraestructura digital centrada en descubrimiento y conexión local.', tags:['SaaS','Local Commerce','Marketplace'], repo:'https://github.com/popnegro/smartbarrio-saas', visual:'local' },
  { n:'06', name:'Confirmá', eyebrow:'WHATSAPP / HEALTHCARE', title:'Una experiencia de confirmación diseñada alrededor del paciente.', desc:'PMV orientado a reducir no-shows y huecos de agenda en clínicas, usando WhatsApp, reprogramación y beneficios por franja horaria.', role:'Product design · Conversational UX · Automation', problem:'Las agendas pierden capacidad cuando las confirmaciones y reprogramaciones dependen de procesos manuales.', outcome:'Un flujo conversacional que organiza confirmación, reprogramación y beneficios alrededor del paciente.', tags:['WhatsApp','Product Design','PMV','Automation'], repo:'https://github.com/popnegro/confirma', visual:'vertical' }
]

const archiveWorks = [
  { n:'01', title:'Brand systems', type:'BRANDING', text:'Identidad visual, key visual y sistemas gráficos desarrollados a lo largo de una trayectoria entre agencias, startups y trabajo independiente.' },
  { n:'02', title:'Digital campaigns', type:'CAMPAIGNS', text:'Campañas y piezas para comunicación digital: RRSS, Meta Ads, Google Ads, email marketing, banners y adaptaciones multiformato.' },
  { n:'03', title:'Visual communication', type:'COMMUNICATION', text:'Diseño publicitario e institucional para múltiples canales, combinando criterio visual, consistencia de marca y adaptación.' },
  { n:'04', title:'Web & interfaces', type:'DIGITAL', text:'Diseño web y UI/UX como puente entre comunicación visual, contenido y experiencias digitales.' }
]

const brands = ['La Proa Com&Mkt', 'Gambler UI', 'Voyenbus.com', 'Ideologik']

function Visual({type}:{type:string}){
  if(type==='ai') return <div className="visual ai"><div className="ai-top">REASONING ENGINE <span>● LIVE</span></div><div className="steps"><b>01</b><i>Discovery</i><b>02</b><i>Analysis</i><b>03</b><i>PMV</i></div><div className="result"><small>PROPOSED PMV</small><strong>Intervention plan</strong><div className="bars"><em/><em/><em/><em/></div></div></div>
  if(type==='map') return <div className="visual map"><div className="map-grid"/><div className="route"/><span className="pin p1"/><span className="pin p2"/><span className="pin p3"/><span className="pin p4"/><div className="map-label">MENDOZA / BUENOS AIRES</div></div>
  if(type==='editorial') return <div className="visual editorial"><small>DEFENSA PENAL · ASESORÍA CORPORATIVA</small><h3>Una experiencia<br/><i>que genera confianza.</i></h3><div className="line"/></div>
  if(type==='local') return <div className="visual local"><div className="local-card"><span>SMART</span><strong>BARRIO</strong><small>Discover local businesses</small></div><div className="orb o1"/><div className="orb o2"/></div>
  if(type==='vertical') return <div className="visual vertical"><div/><div/><div/><div/><div/><div/></div>
  return <div className="visual saas"><div className="browser"><header><span/><span/><span/></header><div className="browser-body"><aside/><main><div className="metric-row"><b/><b/><b/></div><div className="panel"/><div className="panel short"/></main></div></div><div className="stack">WEBSITE → CONTENT → MODULES</div></div>
}

export default function Home(){
 return <main>
  <nav><a className="brand" href="#top">LUIS<span>GRASSO</span></a><div className="navlinks"><a href="#work">Work</a><a href="#services">Services</a><a href="#story">Story</a><a href="#approach">Approach</a><a href="#archive">Archive</a></div><div className="nav-end"><a href="#manifest">Manifest</a><a className="nav-cta" href="mailto:grasso.luis@gmail.com">Contact ↗</a></div></nav>

  <section className="hero" id="top"><div className="eyebrow">PRODUCT DESIGN · UX/UI · WEB · BUSINESS <span>·</span> MENDOZA, ARGENTINA</div><h1>15+ years of<br/><em>turning problems into products.</em></h1><p className="hero-copy">Soy Luis Grasso. Diseñador y constructor digital. Más de 15 años entre comunicación, diseño, web, UX/UI, marketing y tecnología me enseñaron que una buena solución no empieza por la interfaz: empieza por entender qué problema vale la pena resolver y para quién.</p><div className="hero-actions"><a className="hero-link" href="#work">Ver trabajo <span>↓</span></a><a className="hero-secondary" href="#services">Qué puedo resolver</a></div><div className="hero-meta"><span>SELECTED WORK / PRESENT</span><span>DESIGN → USER → BUSINESS → PRODUCT</span></div></section>

  <section className="statement"><p>“El cargo cambia.<br/><strong>El oficio permanece.</strong>”</p><div>01 / CRAFT</div></section>

  <section className="story" id="story"><div className="section-head"><span>THE STORY</span><h2>No cambié de profesión.<br/><em>La fui llevando más lejos.</em></h2></div><div className="story-grid"><div className="story-lead"><p>Durante más de 15 años trabajé entre agencias, startups, empresas y proyectos independientes. Mi recorrido pasó por diseño gráfico, branding, campañas, web, UI/UX, marketing y tecnología.</p><p>Con el tiempo entendí que las etiquetas de cada etapa importan menos que el problema que hay delante. Hoy uso todo ese recorrido para pensar, diseñar y construir productos y sistemas digitales con una mirada que también contempla el negocio.</p></div><div className="timeline"><div><b>01</b><strong>Comunicar</strong><span>Aprender a observar, escuchar y hacer comprensible una idea.</span></div><div><b>02</b><strong>Entender al usuario</strong><span>Pasar de la pieza y la interfaz al contexto, la necesidad y la fricción.</span></div><div><b>03</b><strong>Entender el negocio</strong><span>Objetivos, recursos, operación, adquisición y restricciones también son parte del problema.</span></div><div><b>04</b><strong>Construir producto</strong><span>Convertir criterio y tecnología en algo real, usable y capaz de evolucionar.</span></div></div></div></section>

  <section className="services" id="services"><div className="section-head"><span>WHAT I CAN HELP BUILD</span><h2>Diseño con criterio<br/><em>de negocio.</em></h2></div><div className="service-grid"><div><b>01</b><h3>Definir un producto</h3><p>Ordenar una idea, entender el problema, priorizar y convertir una oportunidad en un alcance posible.</p></div><div><b>02</b><h3>Diseñar una experiencia</h3><p>Arquitectura, UX/UI, contenido e interfaces que hagan más claro el camino entre una necesidad y una acción.</p></div><div><b>03</b><h3>Construir una primera versión</h3><p>MVPs, sitios, aplicaciones y sistemas digitales donde diseño y ejecución trabajan juntos desde el inicio.</p></div><div><b>04</b><h3>Mejorar lo que ya existe</h3><p>Auditar, simplificar y evolucionar productos digitales cuando el problema ya no es empezar, sino decidir qué cambiar.</p></div></div></section>

  <section className="work" id="work"><div className="section-head"><span>SELECTED WORK / PRESENT</span><h2>Problemas que estoy<br/><em>aprendiendo a resolver.</em></h2></div>{projects.map((p)=><article className="project" key={p.name}><div className="project-top"><span>{p.n} / {p.eyebrow}</span><a href={`${p.repo}#readme`} target="_blank" rel="noopener noreferrer">Documentation ↗</a></div><div className="project-grid"><div className="project-copy"><h3>{p.name}</h3><h4>{p.title}</h4><p>{p.desc}</p><div className="project-evidence"><div><small>ROLE</small><span>{p.role}</span></div><div><small>PROBLEM</small><span>{p.problem}</span></div><div><small>WHAT I BUILT</small><span>{p.outcome}</span></div></div><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div><Visual type={p.visual}/></div></article>)}</section>

  <section className="approach" id="approach"><div className="section-head"><span>APPROACH / PRODUCT PRINCIPLES</span><h2>Antes de diseñar,<br/><em>hay que decidir.</em></h2></div><div className="process">{[['01','Understand','Entender el problema, el contexto y lo que realmente necesita resolverse.'],['02','User','Diseñar alrededor de una persona, una necesidad y una situación concreta.'],['03','Business','Considerar objetivos, recursos, operación, adquisición y viabilidad.'],['04','Design','Convertir complejidad en una experiencia clara, consistente y usable.'],['05','Build','Construir lo suficiente para aprender sin agregar complejidad innecesaria.'],['06','Evolve','Medir, observar y mejorar antes de asumir que la primera solución es definitiva.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>

  <section className="capabilities"><div className="section-head"><span>CAPABILITIES</span><h2>Una práctica híbrida.<br/>Un problema a la vez.</h2></div><div className="cap-grid"><p>Brand & Visual Design</p><p>UX / UI</p><p>Digital Campaigns</p><p>Web Applications</p><p>Product Strategy</p><p>SaaS Architecture</p><p>AI Products</p><p>Analytics & Optimization</p></div></section>

  <section className="archive" id="archive"><div className="section-head"><span>ARCHIVE / EXPERIENCE</span><h2>La experiencia detrás<br/><em>del presente.</em></h2></div><p className="archive-intro">No es otro portfolio. Es contexto: trabajos, marcas y disciplinas que construyeron el criterio con el que trabajo hoy.</p><div className="archive-grid">{archiveWorks.map(w=><article key={w.n}><span>{w.n} / {w.type}</span><h3>{w.title}</h3><p>{w.text}</p></article>)}</div><div className="brands"><div className="brands-head"><span>SELECTED BRANDS / EXPERIENCE</span><small>← DRAG / SCROLL →</small></div><div className="brands-track">{brands.map((brand)=><div className="brand-card" key={brand}><span>EXPERIENCE</span><strong>{brand}</strong></div>)}</div></div></section>

  <section className="manifest" id="manifest"><div className="section-head"><span>MANIFEST / PRINCIPLES</span><h2>El oficio no es<br/><em>el cargo.</em></h2></div><div className="manifest-intro"><p>Mi trabajo cambió de forma muchas veces. Lo que permanece es una manera de enfrentar problemas: aprender, comunicar, entender a las personas, considerar el negocio y construir lo que realmente vale la pena.</p></div><div className="manifest-grid"><article><b>01 / LEARN</b><h3>Cada proyecto enseña algo.</h3><p>No necesito llegar con todas las respuestas. Necesito saber observar, preguntar y aprender lo suficiente para tomar una buena decisión.</p></article><article><b>02 / COMMUNICATE</b><h3>Diseñar también es explicar.</h3><p>Antes de convencer, escuchar. Antes de diseñar, entender. Antes de construir, hacer explícito el problema.</p></article><article><b>03 / USER</b><h3>El usuario no es una abstracción.</h3><p>Una solución empieza por una persona, una necesidad y un contexto. La interfaz es una consecuencia de eso.</p></article><article><b>04 / BUSINESS</b><h3>Un producto también es un negocio.</h3><p>Una solución puede ser atractiva y técnicamente correcta y aun así no tener sentido. Objetivos, recursos, costos, operación y oportunidad forman parte del diseño.</p></article><article className="manifest-final"><b>05 / PRODUCT</b><h3>Construir no es el objetivo.</h3><p>El objetivo es resolver algo que importa. La tecnología, el diseño y el producto son medios para llegar ahí.</p></article></div><div className="manifest-line">LEARN → COMMUNICATE → USER → BUSINESS → PRODUCT</div></section>

  <section className="closing"><span>WORKING WITH TEAMS, STARTUPS, AGENCIES & BUSINESSES</span><h2>¿Tenés un problema<br/><em>que valga la pena resolver?</em></h2><p className="closing-copy">Podemos empezar por entenderlo: qué necesita realmente el proyecto, qué tiene sentido construir ahora y qué puede esperar.</p><div className="closing-actions"><a href="mailto:grasso.luis@gmail.com">Start a conversation ↗</a><a href="https://www.linkedin.com/in/luis-grasso" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://github.com/popnegro" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></section>
  <footer><span>LUIS GRASSO / DIGITAL PRODUCT DESIGN</span><span>MENDOZA · ARGENTINA</span><a href="https://github.com/popnegro" target="_blank" rel="noopener noreferrer">github.com/popnegro ↗</a></footer>
 </main>
}