const projects = [
  { n:'01', name:'SmartWeb', eyebrow:'PRODUCT / SAAS', title:'Infraestructura digital para negocios que necesitan crecer.', desc:'Una plataforma para convertir sitios aislados en una infraestructura digital reutilizable: contenido, SEO, WhatsApp, módulos y evolución multi-tenant.', role:'Product design · UX · Development', problem:'Negocios locales con presencia digital fragmentada y procesos que dependen de herramientas separadas.', outcome:'Un sistema reutilizable que conecta presencia web, contenido, adquisición y operación.', tags:['Next.js','TypeScript','Supabase','PostgreSQL','Vercel'], repo:'https://github.com/popnegro/smartweb', visual:'saas' },
  { n:'02', name:'MuniBrain', eyebrow:'AI / CIVIC TECH', title:'De un problema público a un PMV accionable.', desc:'Motor de descubrimiento y análisis que transforma consultas en propuestas estructuradas con alcance, presupuesto, timeline, KPIs y riesgos.', role:'Product concept · AI UX · Frontend', problem:'Ideas y necesidades difíciles de convertir rápidamente en iniciativas concretas y evaluables.', outcome:'Una experiencia que estructura el problema y lo traduce en una propuesta de intervención.', tags:['Next.js 15','React 19','AI UX','Recharts','shadcn/ui'], repo:'https://github.com/popnegro/munibrain', visual:'ai' },
  { n:'03', name:'Grupo Comunicarte', eyebrow:'PLATFORM / COMMERCIAL', title:'Una plataforma comercial para hacer visible el inventario.', desc:'Ecosistema que conecta landing pública, mapa de soportes, inventario, dashboard, MediaKit y gestión comercial.', role:'UX · Product design · Web development', problem:'Inventario y oportunidades comerciales que necesitan una capa digital más clara para ser descubiertos y gestionados.', outcome:'Un sistema que conecta ubicación, inventario y herramientas comerciales en una misma experiencia.', tags:['React','TypeScript','Maps','Dashboard','MediaKit'], repo:'https://github.com/popnegro/grupo-comunicarte-refactoring', visual:'map' },
  { n:'04', name:'Emilia Sandobar', eyebrow:'UX / LEGAL', title:'Una experiencia digital que convierte confianza en consulta.', desc:'Sitio editorial para servicios legales con arquitectura por rutas, SEO técnico, formularios, CTAs de consulta y validación E2E.', role:'UX/UI · Content structure · Development', problem:'Un servicio profesional necesita explicar valor y generar confianza antes del primer contacto.', outcome:'Una experiencia editorial enfocada en claridad, autoridad y solicitud de consulta.', tags:['React 19','TypeScript','Vite','Tailwind','Playwright'], repo:'https://github.com/popnegro/abogadasandobar', visual:'editorial' },
  { n:'05', name:'SmartBarrio', eyebrow:'LOCAL COMMERCE', title:'Presencia y descubrimiento para la economía de proximidad.', desc:'Exploración de marketplace y servicios digitales para negocios de barrio, conectando descubrimiento, presencia y oportunidades comerciales.', role:'Product concept · UX · Business model', problem:'Los negocios de proximidad necesitan ser encontrados y conectarse mejor con su demanda local.', outcome:'Una propuesta de infraestructura digital centrada en descubrimiento y conexión local.', tags:['SaaS','Local Commerce','Marketplace'], repo:'https://github.com/popnegro/smartbarrio-saas', visual:'local' },
  { n:'06', name:'Confirmá', eyebrow:'WHATSAPP / HEALTHCARE', title:'Una experiencia de confirmación diseñada alrededor del paciente.', desc:'PMV orientado a reducir no-shows y huecos de agenda en clínicas, usando WhatsApp, reprogramación y beneficios por franja horaria.', role:'Product design · Conversational UX · Automation', problem:'Las agendas pierden capacidad cuando las confirmaciones y reprogramaciones dependen de procesos manuales.', outcome:'Un flujo conversacional que organiza confirmación, reprogramación y beneficios alrededor del paciente.', tags:['WhatsApp','Product Design','PMV','Automation'], repo:'https://github.com/popnegro/confirma', visual:'vertical' }
]

const archiveWorks = [
  { n:'01', title:'Brand systems', type:'BRANDING', text:'Identidad visual, key visual y sistemas gráficos desarrollados a lo largo de una trayectoria entre agencias, startups y trabajo independiente.' },
  { n:'02', title:'Digital campaigns', type:'CAMPAIGNS', text:'Campañas y piezas para comunicación digital: RRSS, Meta Ads, Google Ads, email marketing, banners y adaptaciones multiformato.' },
  { n:'03', title:'Visual communication', type:'COMMUNICATION', text:'Diseño publicitario e institucional para múltiples canales, combinando criterio visual, consistencia de marca y adaptación.' },
  { n:'04', title:'Web & interfaces', type:'DIGITAL', text:'Diseño web y UI/UX como puente entre comunicación visual, contenido y experiencias digitales.' }
]

const brands = ['La Proa Com&Mkt', 'Gambler UI', 'Voyenbus.com', 'Ideologik']

function Visual({type}:{type:string}){
  if(type==='ai') return <div className="visual ai"><div className="ai-top">REASONING ENGINE <span>● LIVE</span></div><div className="steps"><b>01</b><i>Discovery</i><b>02</b><i>Analysis</i><b>03</b><i>PMV</i></div><div className="result"><small>PROPOSED PMV</small><strong>Intervention plan</strong><div className="bars"><em/><em/><em/><em/></div></div></div>
  if(type==='map') return <div className="visual map"><div className="map-grid"/><div className="route"/><span className="pin p1"/><span className="pin p2"/><span className="pin p3"/><span className="pin p4"/><div className="map-label">MENDOZA / BUENOS AIRES</div></div>
  if(type==='editorial') return <div className="visual editorial"><small>DEFENSA PENAL · ASESORÍA CORPORATIVA</small><h3>Una experiencia<br/><i>que genera confianza.</i></h3><div className="line"/></div>
  if(type==='local') return <div className="visual local"><div className="local-card"><span>SMART</span><strong>BARRIO</strong><small>Discover local businesses</small></div><div className="orb o1"/><div className="orb o2"/></div>
  if(type==='vertical') return <div className="visual vertical"><div/><div/><div/><div/><div/><div/></div>
  return <div className="visual saas"><div className="browser"><header><span/><span/><span/></header><div className="browser-body"><aside/><main><div className="metric-row"><b/><b/><b/></div><div className="panel"/><div className="panel short"/></main></div></div><div className="stack">WEBSITE → CONTENT → MODULES</div></div>
}

export default function Home(){
 return <main>
  <nav><a className="brand" href="#top">LUIS<span>GRASSO</span></a><div className="navlinks"><a href="#work">Work</a><a href="#services">Services</a><a href="#story">Story</a><a href="#approach">Approach</a><a href="#archive">Archive</a></div><div className="nav-end"><a href="#manifest">Manifest</a><a className="nav-cta" href="mailto:grasso.luis@gmail.com">Contact ↗</a></div></nav>
  <section className="hero" id="top"><div className="eyebrow">DIGITAL PRODUCT DESIGN · UX/UI · WEB · PRODUCT <span>·</span> MENDOZA, ARGENTINA</div><h1>15+ years from<br/><em>design to digital products.</em></h1><p className="hero-copy">Soy Luis Grasso. Diseñador y constructor de experiencias y productos digitales. Después de más de 15 años entre diseño gráfico, branding, campañas, web, UX/UI, marketing y tecnología, hoy trabajo en la intersección entre diseño, producto y ejecución.</p><div className="hero-actions"><a className="hero-link" href="#work">Ver trabajo <span>↓</span></a><a className="hero-secondary" href="#services">Qué puedo construir</a></div><div className="hero-meta"><span>SELECTED WORK / PRESENT</span><span>DESIGN → UX → WEB → PRODUCT</span></div></section>
  <section className="statement"><p>“No cambié de profesión.<br/><strong>La fui llevando más lejos.</strong>”</p><div>01 / EVOLUTION</div></section>
  <section className="story" id="story"><div className="section-head"><span>THE STORY</span><h2>Una evolución<br/><em>orgánica.</em></h2></div><div className="story-grid"><div className="story-lead"><p>Durante más de 15 años trabajé para agencias, startups, empresas y proyectos independientes, primero desde la comunicación visual y el diseño, y progresivamente incorporando web, UX/UI, marketing y tecnología.</p><p>Hoy esa experiencia converge en una forma distinta de trabajar: entender un problema, diseñar una solución y construir el sistema digital que la hace posible.</p></div><div className="timeline"><div><b>01</b><strong>Diseño gráfico</strong><span>Identidad, campañas, publicidad y comunicación visual.</span></div><div><b>02</b><strong>Diseño digital</strong><span>Web, interfaces, contenido, RRSS y experiencias multicanal.</span></div><div><b>03</b><strong>UX + marketing</strong><span>Experiencia, adquisición, analítica y optimización.</span></div><div><b>04</b><strong>Producto</strong><span>Apps, SaaS, plataformas, AI y sistemas digitales.</span></div></div></div></section>
  <section className="services" id="services"><div className="section-head"><span>WHAT I CAN HELP BUILD</span><h2>Diseño que entiende<br/><em>el negocio.</em></h2></div><div className="service-grid"><div><b>01</b><h3>Para empresas y equipos</h3><p>Experiencias web, interfaces y sistemas digitales cuando el producto necesita más claridad, consistencia y capacidad de evolución.</p></div><div><b>02</b><h3>Para startups y founders</h3><p>De una idea ambigua a un MVP: definición, UX, diseño de producto y una primera implementación funcional.</p></div><div><b>03</b><h3>Para agencias y estudios</h3><p>Refuerzo de diseño, UI/UX, landing pages, campañas digitales y ejecución web para proyectos que necesitan resolver rápido.</p></div><div><b>04</b><h3>Para negocios y profesionales</h3><p>Presencia digital, landing pages y experiencias orientadas a generar consultas, oportunidades comerciales y una mejor primera impresión.</p></div></div></section>
  <section className="work" id="work"><div className="section-head"><span>SELECTED WORK / PRESENT</span><h2>Lo que estoy<br/><em>construyendo hoy.</em></h2></div>{projects.map((p)=><article className="project" key={p.name}><div className="project-top"><span>{p.n} / {p.eyebrow}</span><a href={p.repo} target="_blank" rel="noopener noreferrer">Repository ↗</a></div><div className="project-grid"><div className="project-copy"><h3>{p.name}</h3><h4>{p.title}</h4><p>{p.desc}</p><div className="project-evidence"><div><small>ROLE</small><span>{p.role}</span></div><div><small>PROBLEM</small><span>{p.problem}</span></div><div><small>OUTCOME</small><span>{p.outcome}</span></div></div><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div><Visual type={p.visual}/></div></article>)}</section>
  <section className="approach" id="approach"><div className="section-head"><span>APPROACH</span><h2>De la ambigüedad<br/><em>a algo real.</em></h2></div><div className="process">{[['01','Discover','Entender el problema antes de diseñar la solución.'],['02','Define','Convertir necesidades en alcance, prioridades y métricas.'],['03','Design','Crear sistemas de interfaz claros, consistentes y humanos.'],['04','Build','Construir con una arquitectura que pueda evolucionar.'],['05','Validate','Medir, probar y corregir antes de agregar complejidad.'],['06','Evolve','Convertir el PMV en producto sin rehacer lo construido.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
  <section className="capabilities"><div className="section-head"><span>CAPABILITIES</span><h2>Creative thinking.<br/>Technical execution.</h2></div><div className="cap-grid"><p>Brand & Visual Design</p><p>UX / UI</p><p>Digital Campaigns</p><p>Web Applications</p><p>Product Strategy</p><p>SaaS Architecture</p><p>AI Products</p><p>Analytics & Optimization</p></div></section>
  <section className="archive" id="archive"><div className="section-head"><span>ARCHIVE / EXPERIENCE</span><h2>De dónde<br/><em>vengo.</em></h2></div><p className="archive-intro">El presente muestra lo que construyo hoy. El archivo muestra la experiencia que lo hizo posible.</p><div className="archive-grid">{archiveWorks.map(w=><article key={w.n}><span>{w.n} / {w.type}</span><h3>{w.title}</h3><p>{w.text}</p></article>)}</div><div className="brands"><div className="brands-head"><span>SELECTED BRANDS / EXPERIENCE</span><small>← DRAG / SCROLL →</small></div><div className="brands-track">{brands.map((brand)=><div className="brand-card" key={brand}><span>EXPERIENCE</span><strong>{brand}</strong></div>)}</div></div></section>
  <section className="manifest" id="manifest"><div className="section-head"><span>MANIFEST</span><h2>Cómo<br/><em>pienso.</em></h2></div><div className="manifest-intro"><p>Diseñar no es solamente hacer que algo se vea bien. Es aprender, entender, comunicar y tomar decisiones que tengan sentido para las personas y para el negocio.</p></div><div className="manifest-grid"><article><b>01 / LEARNING</b><h3>Aprender antes de construir.</h3><p>Cada proyecto empieza por entender el contexto: personas, restricciones, mercado, tecnología y lo que realmente necesita resolverse.</p></article><article><b>02 / COMMUNICATION</b><h3>Hacer comprensible lo complejo.</h3><p>El diseño es una herramienta de comunicación. Una buena solución reduce fricción y permite entender qué hacer, por qué hacerlo y qué esperar.</p></article><article><b>03 / USER</b><h3>La tecnología no es el producto.</h3><p>El producto es la experiencia que la tecnología permite. Por eso la interfaz, el contenido, el flujo y el contexto importan tanto como el código.</p></article><article><b>04 / BUSINESS</b><h3>Lo útil también tiene que funcionar.</h3><p>Una solución necesita ser viable: adquisición, conversión, operación, costos y capacidad de evolucionar forman parte del diseño.</p></article><article className="manifest-final"><b>05 / PRODUCT</b><h3>No todo necesita una app.</h3><p>Primero hay que descubrir qué vale la pena construir. Después, elegir la menor cantidad de complejidad capaz de resolverlo bien.</p></article></div><div className="manifest-line">DESIGN → COMMUNICATION → USER → BUSINESS → PRODUCT</div></section>
  <section className="closing"><span>WORKING WITH TEAMS, STARTUPS, AGENCIES & BUSINESSES</span><h2>¿Tenés un problema<br/><em>digital que resolver?</em></h2><p className="closing-copy">Podemos empezar por definir qué necesita realmente el proyecto, qué vale la pena construir ahora y qué puede esperar.</p><div className="closing-actions"><a href="mailto:grasso.luis@gmail.com">Start a conversation ↗</a><a href="https://www.linkedin.com/in/luis-grasso" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://github.com/popnegro" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></section>
  <footer><span>LUIS GRASSO / DIGITAL PRODUCT DESIGN</span><span>MENDOZA · ARGENTINA</span><a href="https://github.com/popnegro" target="_blank" rel="noopener noreferrer">github.com/popnegro ↗</a></footer>
 </main>
}